### ISSUE TITLE
Cargo test failed in "test player::in_room::tests::player_in_room"

### ISSUE THREAD

**Issue by GustavoLR548** [drwhut/tabletop_club_lobby_server#2]
After running ```cargo test``` inside of the project, I have received the following message

```sh
running 23 tests
test config::tests::read_and_write ... ok
test config::tests::update_task_default_file ... ok
test config::tests::valid_default ... ok
test config::tests::update_task_no_file ... ok
test config::tests::update_task_modified_file ... ok
test connection::tests::check_shutdown ... ok
test connection::tests::accept_plain ... ok
test config::tests::read_err ... ok
test connection::tests::accept_tls ... ok
test room::tests::test_client_close ... ok
test room::tests::test_client_drop ... ok
test room::tests::test_host_error ... ok
test room::tests::test_senario ... ok
test room::tests::test_shutdown ... ok
test room::tests::test_time_limit ... ok
test room::tests::test_time_limit_change ... ok
test room_code::tests::check_conversion ... ok
test room_code::tests::check_default ... ok
test room_code::tests::check_profanity ... ok
test player::tests::send_close ... ok
test player::joining::tests::player_joining ... ok
test player::in_room::tests::player_in_room ... FAILED
test room_code::tests::check_random ... ok

failures:

---- player::in_room::tests::player_in_room stdout ----
thread 'player::in_room::tests::player_in_room' panicked at src/player/in_room.rs:765:39:
server function failed: SendError(PlayerJoined(9))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'player::in_room::tests::player_in_room' panicked at src/player/in_room.rs:783:9:
error receiving message from server: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })


failures:
    player::in_room::tests::player_in_room

test result: FAILED. 22 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 18.09s

error: test failed, to rerun pass `--lib`
```

It seems that there is something wrong with the test "test player::in_room::tests::player_in_room" I am not sure if this is something that I did wrong, but I would love to know your opinion.

**Comment by GustavoLR548** [comment]
Ok for some reason it just worked now after resetting

**Comment by drwhut** [comment]
Yeah, there's a note about this in the README - I'm still not exactly sure what causes it (I'm guessing its a UNIX pipe being accessed from separate threads at the same time), but it only happens rarely.
